### ISSUE TITLE
Webpack not able to bundle datadog-lambda-js

### ISSUE THREAD

**Issue by mohitm94** [DataDog/datadog-lambda-js#184]
## Expected Behavior
datadog-lambda-js handler doesn't throw any errors

## Actual Behavior
webpack is not able to package datadog-lambda-js handler due to dependencies on lambda runtime.

## Steps to Reproduce the Problem

  1. Follow the steps mentioned here. https://docs.datadoghq.com/serverless/installation/nodejs/?tab=custom#using-the-package
  2. Run `serverless package` command.
  3. Webpack fails with an error.

## Specifications

  - Datadog Lambda Layer version: N.A
  - Node version: 14.x
  
## Stacktrace
  
  ```
 ERROR in ./node_modules/datadog-lambda-js/dist/handler.js 8:11-52
Module not found: Error: Can't resolve '/var/runtime/UserFunction' in '/Users/mohitm/dev/git/serverless-request-management/node_modules/datadog-lambda-js/dist'
resolve '/var/runtime/UserFunction' in '/Users/mohitm/dev/git/serverless-request-management/node_modules/datadog-lambda-js/dist'
  using description file: /Users/mohitm/dev/git/serverless-request-management/node_modules/datadog-lambda-js/package.json (relative path: ./dist)
    root path /Users/mohitm/dev/git/serverless-request-management
      using description file: /Users/mohitm/dev/git/serverless-request-management/package.json (relative path: ./var/runtime/UserFunction)
        no extension
          /Users/mohitm/dev/git/serverless-request-management/var/runtime/UserFunction doesn't exist
        .js
          /Users/mohitm/dev/git/serverless-request-management/var/runtime/UserFunction.js doesn't exist
        .json
          /Users/mohitm/dev/git/serverless-request-management/var/runtime/UserFunction.json doesn't exist
        .wasm
          /Users/mohitm/dev/git/serverless-request-management/var/runtime/UserFunction.wasm doesn't exist
        as directory
          /Users/mohitm/dev/git/serverless-request-management/var/runtime/UserFunction doesn't exist
    No description file found in /var/runtime or above
    no extension
      /var/runtime/UserFunction doesn't exist
    .js
      /var/runtime/UserFunction.js doesn't exist
    .json
      /var/runtime/UserFunction.json doesn't exist
    .wasm
      /var/runtime/UserFunction.wasm doesn't exist
    as directory
      /var/runtime/UserFunction doesn't exist

webpack compiled with 1 error and 2 warnings in 366 ms

  ```

Webpack config
```
const slsw = require('serverless-webpack');
const CopyPlugin = require('copy-webpack-plugin');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  externals: ['dd-trace', 'datadog-lambda-js', nodeExternals()],
  externalsPresets: {
    node: true
  },
  optimization: {
    minimize: false
  },
  entry: slsw.lib.entries,
  target: 'node',
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  devtool: 'inline-cheap-module-source-map'
};

```
Webpack serverless config
```
webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: tests/ # Provide a glob for files to ignore
    concurrency: 6
    serializedCompile: true
    includeModules:
      forceExclude:
        - dd-trace
        - datadog-lambda-js
```
function definition in serverless.yml
``` 
functions:
  auth:
    handler: node_modules/datadog-lambda-js/dist/handler.handler
    environment:
      DD_LAMBDA_HANDLER: functions/auth.handler
    timeout: 30
```
