### ISSUE TITLE
Docker lambda container with serverless framework and webpack

### ISSUE THREAD

**Issue by dave-jumptech** [DataDog/datadog-lambda-js#272]
Hi, I'm looking for some guidance on how to integrate datadog-lambda-js when using the [serverless framework](https://www.serverless.com/framework/docs/providers/aws/guide/functions#referencing-container-image-as-a-target) with [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack) (for typescript support) and containers.

It seems that datadog-lambda-js does not play well with serverless when using functions in containes.

I followed these instructions: https://docs.datadoghq.com/serverless/installation/nodejs/?tab=containerimage, setting up my function in serverless as:
```yaml
test:
  image:
    platform: linux/amd64
    name: test
    command:
      - node_modules/datadog-lambda-js/dist/handler.handler
    entryPoint:
      - '/lambda-entrypoint.sh'
  description: 'test fn'
  timeout: 10
  environment:
    DD_LAMBDA_HANDLER: src/test/test.test
```

Set up webpack config in serverless.yml:
```yaml
  webpack:
    keepOutputDirectory: true
    includeModules: false
    forceExclude:
      - aws-sdk
      - datadog-lambda-js
      - dd-trace
```

And my Dockerfile installs the `node_modules` and copies in the DD extension:

```Dockerfile
FROM amazon/aws-lambda-nodejs:14
COPY package.json package-lock.json ./
RUN npm ci --production

COPY --from=datadog/lambda-extension@sha256:7872a81edafc7e47f07ec758a4b0b596b042dba2cd9aa630de3e071b3a3f80d2 /opt/extensions/ /opt/extensions
COPY .webpack/service .
```
And the dd libs are in the package.json dependencies:
```json
  "dependencies": {
    "datadog-lambda-js": "^5.73.0",
    "dd-trace": "^2.3.1"
  },
```

When I run serverless deploy, because my image command is set to `node_modules/datadog-lambda-js/dist/handler.handler`, the serverless-webpack plugin uses the dd handler as the entry and not my actual function entry `src/scan/test.test` , so that my .webpack  directory is:

```
.webpack
  /service
    /node_modules
      /datadog-lambda-js
        /dist
          handler.js
```

i.e. serverless webpack has packaged the datadog handler, not my function handler. It should be:
```
.webpack
  /service
    /src
      /test
        test.js
```

Do you have any thoughts on how to address this issue? Is there another way to start the datadog handler - in the entrypoint, maybe? Could I instrument my handler function in webpack somehow?

Thanks
