### ISSUE TITLE
BUG: Upgrading to 5.76.0 throws TypeError

### ISSUE THREAD

**Issue by bhb603** [DataDog/datadog-lambda-js#606]
## Expected Behavior

No errors in my lambdas 😄  

## Actual Behavior

After upgrading `serverless-plugin-datadog` from 5.75.0 -> 5.76.0, the TypeErrors (stacktrace below) are thrown upon Lambda invocation.

Note that v5.75.0 worked fine.

## Steps to Reproduce the Problem

  1. Upgrade to serverless-plugin-datadog 5.76.0
  1. Deploy and invoke lambda
  1. Observe errors in logs

## Specifications

  - Serverless Framework version: 3.40
  - Datadog Serverless Plugin version: 5.76.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Nodejs 20.x
  
## Stacktrace
  
  ```
  2025-01-09T20:45:52.863Z	447ffbbf-4c6a-4872-bab8-2748617d52b6	ERROR	{"status":"error","message":"Cannot read properties of undefined (reading 'toString')","name":"TypeError","stack":"TypeError: Cannot read properties of undefined (reading 'toString')
    at DatadogSpanContext.toTraceId (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/opentracing/span_context.js:40:26)
    at SpanContextWrapper.toTraceId (/opt/nodejs/node_modules/datadog-lambda-js/trace/span-context-wrapper.js:27:33)
    at TraceContextExtractor.addTraceContextToXray (/opt/nodejs/node_modules/datadog-lambda-js/trace/context/extractor.js:122:41)
    at TraceContextExtractor.<anonymous> (/opt/nodejs/node_modules/datadog-lambda-js/trace/context/extractor.js:80:34)
    at step (/opt/nodejs/node_modules/datadog-lambda-js/trace/context/extractor.js:33:23)
    at Object.next (/opt/nodejs/node_modules/datadog-lambda-js/trace/context/extractor.js:14:53)
    at /opt/nodejs/node_modules/datadog-lambda-js/trace/context/extractor.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/nodejs/node_modules/datadog-lambda-js/trace/context/extractor.js:4:12)
    at TraceContextExtractor.extract (/opt/nodejs/node_modules/datadog-lambda-js/trace/context/extractor.js:55:16)"}
  ```

**Comment by purple4reina** [comment]
Hey @bhb603, thanks for reporting this! As we look into it, can you tell us a bit about the functionality of your lambda? Specifically, which AWS event types is it processing? How have you configured trace propagation (if at all)?

**Comment by bhb603** [comment]
Hi @purple4reina ,

Our Lambda is invoked via [APIGateway V1](https://github.com/serverless/serverless/blob/v3.40.0/docs/providers/aws/events/apigateway.md#rest-api-api-gateway-v1), i.e. the serverless.yml function definition is something like:
```yml
functions:
  my_function:
    handler: handler.hello
    events:
      - http:
          path: /example
          method: post
```

I don't believe we have any trace propagation, we have basically a default setup as described in the [docs](https://docs.datadoghq.com/serverless/aws_lambda/installation/nodejs/?tab=serverlessframework) for the Nodejs + Serverless framework.

The other possibly-relevant info is that we use Typescript and esbuild, so we're using `serverless-esbuild`  to bundle.

Our serverless.yml has the following:
```yml
provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs20.x
  region: us-west-2
  stage: staging
  versionFunctions: false
  architecture: x86_64

plugins:
  - serverless-plugin-datadog
  - serverless-esbuild
  - serverless-offline
  - serverless-offline-watcher
 
esbuild:
  bundle: true
  minify: false
  sourcemap: true
  exclude: ['dd-trace', 'datadog-lambda-js']
datadog:
  addExtension: true
  apiKey: ***
  version: ${env:DD_VERSION}
```

Package.json:
```json
    "esbuild": "0.24.2",
    "serverless": "^3.40.0",
    "serverless-esbuild": "^1.54.6",
    "serverless-offline": "^14.4.0",
    "serverless-offline-watcher": "^1.1.0",
    "serverless-plugin-datadog": "5.75.0",
```

LMK if you need any more info!

It's been a while since we set this up, so I'm not as steeped in all the config options and nuances; we've been using DataDog for some time, and all I know is it worked fine until v5.76.0, which caused the errors described above.
