### ISSUE TITLE
Custom traces not forwarded to DataDog when Kinesis subscription used

### ISSUE THREAD

**Issue by a-h** [DataDog/datadog-lambda-js#90]
## Background

We created an example repository that uses the Serverless Framework plugin and the Lambda Forwarder to push metrics and DataDog Traces to DataDog. It was based on the standard Serverless Framework TypeScript template `sls create --template=aws-nodejs-typescript`:

### serverless.yaml

```yaml
service:
  name: datadog-test

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  datadog:
    addLayers: true
    logLevel: "info"
    flushMetricsToLogs: true
    site: datadoghq.eu
    enableXrayTracing: true
    enableDDTracing: false
    enableTags: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-plugin-datadog

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
```

The DataDog trace library was configured to split requests by domain:

### tracer.ts

```typescript
import ddtrace from "dd-trace";
const tracer = ddtrace.init();
tracer.use("http", {
  splitByDomain: true,
});
export default tracer;
```

The handler makes a couple of HTTP requests, logs a metric and some spans:

### handler.ts

```typescript
import tracer from "./tracer";
import { APIGatewayProxyHandler } from "aws-lambda";
import "source-map-support/register";
import fetch from "node-fetch";
import { datadog, sendDistributionMetric } from "datadog-lambda-js";

export const handler: APIGatewayProxyHandler = async (_event, _context) => {
  const jsonSpan = tracer.startSpan("call_json_placeholder")
  await fetch("https://jsonplaceholder.typicode.com/todos/1");
  jsonSpan.finish()
  try {
    await fetch("https://httpstat.us/500");
  } catch(e) {
    console.log("error calling httpstat.us", e);
  }
  sendDistributionMetric("randomValue", Math.random()); 
  return {
    statusCode: 200,
    body: JSON.stringify({ msg: "ok" }),
  };
};

export const hello = datadog(handler);
```

We use this Lambda to test that our platform observability is working OK.

It _was_ working as expected, but a compliance requirement then required us to create a subscription on our CloudWatch Log Groups to export them to another service. It's only possible to have a single subscription filter on a CloudWatch Log Group (https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html), so the Lambda forwarder stopped executing.

To get around this, we set up a single Kinesis stream following the blog post at https://docs.datadoghq.com/logs/guide/send-aws-services-logs-with-the-datadog-kinesis-firehose-destination/?tab=kinesisfirehosedeliverystream

With the Kinesis integration in place, we now have logs coming in to DataDog (and placed in our audit systems), but not DataDog traces.

In practice, this means, that in the above example, the `call_json_placeholder` span isn't shown at all within DataDog.

We were expecting the Kinesis delivery to be able to handle spans, however, looking at https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/lambda_function.py#L91 it looks like the forwarder has some logic built-in to do something special with spans. Perhaps this is missing from the DataDog Kinesis subscription?

What's the correct way to deal with this?

## Expected Behavior

Expected the trace details to be shown within DataDog.

## Actual Behavior

No trace details shown.

## Steps to Reproduce the Problem

  1. Create the template as above.
  1. Remove the CloudWatch Filter subscription from the Lambda Forwarder and replace with Kinesis stream.
  1. Observe that no traces now appear in DataDog.

## Specifications

```json
{
  "name": "datadog-test",
  "version": "1.0.0",
  "description": "Serverless webpack example using Typescript",
  "main": "handler.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@types/node-fetch": "^2.5.7",
    "datadog-lambda-js": "^2.24.0",
    "dd-trace": "^0.22.2",
    "node-fetch": "^2.6.0",
    "source-map-support": "^0.5.10"
  },
  "devDependencies": {
    "@types/aws-lambda": "^8.10.17",
    "@types/node": "^10.12.18",
    "fork-ts-checker-webpack-plugin": "^3.0.1",
    "serverless": "^1.74.1",
    "serverless-plugin-datadog": "^1.0.1",
    "serverless-webpack": "^5.2.0",
    "ts-loader": "^5.3.3",
    "typescript": "^3.2.4",
    "webpack": "^4.29.0",
    "webpack-node-externals": "^1.7.2"
  },
  "author": "The serverless webpack authors (https://github.com/elastic-coders/serverless-webpack)",
  "license": "MIT"
}
```
